### ISSUE TITLE
Callback result of addEvent

### ISSUE THREAD

**Issue by YN-Ohtsuki** [recruit-lifestyle/TreasureDataSDK#2]
I currently use v1.0.0.

Would you please kindly let me know how I can get callback result of addEvent method?
I would like to know if sending data to TreasureData successfully completed or not.

So, maybe I would like one of enum Result with responseJason or similar result.

Your earliest reply would be appreciated.
Thank you in advance.

Another question:
Is it possible to add data just to the queue and uploadAllStoredEvents when the app becomes background status?

**Comment by uny** [comment]
> Would you please kindly let me know how I can get callback result of addEvent method?

There is no way to get the result.
The SDK automatically retries or saves the events on proper way when uploading fails.
Why do you want to know the result?

> Is it possible to add data just to the queue and uploadAllStoredEvents when the app becomes background status?

Yes, you can.
