### ISSUE TITLE
Building for Swift 2.3

### ISSUE THREAD

**Issue by Lunavast** [recruit-lifestyle/TreasureDataSDK#4]
Do you have any detailed instruction to build this for Swift 2.3?

We had been using your TreasureDataSDK for Swift 2.2 with XCode 7.3.
Recently, we added some new features to our iOS app that requires XCode 8.0. So, we would like to use this framework for Swift 2.3 for XCode8.

**Comment by uny** [comment]
We do not support Swift 2.3.
If you could, pull request would be appreciated.
(We are currently using Xcode 8.2.1...)
